# Generated by Django 5.1 on 2024-09-02 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
