# Generated by Django 5.1 on 2024-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookh', '0002_book_page_count_book_price_book_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
